# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeomCalculator
                                 A QGIS plugin
 This plugin calcs geometric indicators
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-05-21
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Roman
        email                : philw7321980@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant 
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
import qgis
from qgis.core import QgsField, QgsExpression, QgsExpressionContext, QgsExpressionContextUtils, edit
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .geom_calc_dockwidget import GeomCalculatorDockWidget
import os.path


class GeomCalculator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeomCalculator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Geometric Calculator')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'GeomCalculator')
        self.toolbar.setObjectName(u'GeomCalculator')

        #print "** INITIALIZING GeomCalculator"

        self.pluginIsActive = False
        self.dockwidget = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeomCalculator', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/geom_calc/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""
        self.dockwidget.comboBox.clear()

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD GeomCalculator"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Geometric Calculator'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING GeomCalculator"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = GeomCalculatorDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
            #загрузим все слои в выпадающий список
            def checkLayers():
                self.dockwidget.comboBox.clear()
                curLayers = qgis.core.QgsProject.instance().layerTreeRoot().layerOrder()
                layerNames = []
                for cL in curLayers:
                    layerNames.append(cL.name())
                self.dockwidget.comboBox.addItems(layerNames)
            checkLayers()

            def calculate():
                #выбранный слой
                curLayers = qgis.core.QgsProject.instance().layerTreeRoot().layerOrder()
                if not curLayers: return
                sLayerIndex = self.dockwidget.comboBox.currentIndex()
                selectedLayer = curLayers[sLayerIndex]
                #добавляем атрибуты в таблицу если их нет
                atrrs = selectedLayer.dataProvider().fields().names()
                if 'Area' not in atrrs and 'Perimeter' not in atrrs and 'fCompact' not in atrrs and 'iCompact' not in atrrs:
                    res = selectedLayer.dataProvider().addAttributes([QgsField('Area', QVariant.Double), \
                                                                    QgsField('Perimeter', QVariant.Double),\
                                                                    QgsField('fCompact', QVariant.Double),\
                                                                    # QgsField('iCompactness', QVariant.Double),\
                                                                    ])
                    selectedLayer.updateFields()
                #составляем выражения для атрибутов
                area = QgsExpression('$area * 1e2')
                per = QgsExpression('$perimeter')
                fComp = QgsExpression('$perimeter/(4*sqrt($area))')
                # iComp = QgsExpression('')

                context = QgsExpressionContext()
                context.appendScopes(
                    QgsExpressionContextUtils.globalProjectLayerScopes(selectedLayer))
                #загружаем значения выражений для атрибутов
                with edit(selectedLayer):
                    for f in selectedLayer.getFeatures():
                        context.setFeature(f)
                        f['Area'] = area.evaluate(context)
                        f['Perimeter'] = per.evaluate(context)
                        f['fCompact'] = fComp.evaluate(context)
                        # f['iCompact'] = fComp.evaluate(context)
                        selectedLayer.updateFeature(f)

            self.dockwidget.pushButton.clicked.connect(calculate)
            self.dockwidget.check.clicked.connect(checkLayers)
